GAME_NAMES = (
    # Clásicos
    'Pong',
    'Space Invaders',
    'Pac-Man',
    'Donkey Kong',
    'Asteroids',
    'Centipede',
    'Galaga',
    'Frogger',
    'Defender',
    'Missile Command',
    # Nintendo
    'Super Mario Bros.',
    'Super Mario World',
    'Super Mario 64',
    'The Legend of Zelda',
    'A Link to the Past',
    'Ocarina of Time',
    "Majora's Mask",
    'Breath of the Wild',
    'Tears of the Kingdom',
    'Metroid',
    'Super Metroid',
    'Metroid Prime',
    'Pokémon Red',
    'Pokémon Blue',
    'Pokémon Gold',
    'Pokémon Silver',
    'Pokémon Ruby',
    'Pokémon Sapphire',
    'Pokémon Sword',
    'Pokémon Shield',
    'Pokémon Scarlet',
    'Pokémon Violet',
    'Animal Crossing',
    'Animal Crossing: New Horizons',
    'Kirby’s Dream Land',
    'Super Smash Bros.',
    'Super Smash Bros. Ultimate',
    'Splatoon',
    'Splatoon 2',
    'Splatoon 3',
    'Mario Kart 8 Deluxe',
    # PlayStation
    'Final Fantasy VII',
    'Final Fantasy VIII',
    'Final Fantasy IX',
    'Final Fantasy X',
    'Final Fantasy XV',
    'Final Fantasy XVI',
    'God of War',
    'God of War Ragnarök',
    'Gran Turismo',
    'Gran Turismo 7',
    'The Last of Us',
    'The Last of Us Part II',
    'Uncharted',
    "Uncharted 4: A Thief's End",
    'Bloodborne',
    "Demon's Souls",
    'Shadow of the Colossus',
    'Ratchet & Clank',
    'Jak and Daxter',
    'Horizon Zero Dawn',
    'Horizon Forbidden West',
    'Ghost of Tsushima',
    'Spider-Man',
    'Spider-Man: Miles Morales',
    # Xbox / Microsoft
    'Halo: Combat Evolved',
    'Halo 2',
    'Halo 3',
    'Halo Infinite',
    'Gears of War',
    'Gears 5',
    'Forza Motorsport',
    'Forza Horizon 4',
    'Forza Horizon 5',
    'Fable',
    'Sea of Thieves',
    'Microsoft Flight Simulator',
    # PC clásicos
    'Doom',
    'Doom II',
    'Quake',
    'Half-Life',
    'Half-Life 2',
    'Counter-Strike',
    'Counter-Strike: Global Offensive',
    'Team Fortress 2',
    'StarCraft',
    'StarCraft II',
    'Warcraft III',
    'World of Warcraft',
    'Diablo',
    'Diablo II',
    'Diablo III',
    'Diablo IV',
    'The Sims',
    'The Sims 2',
    'The Sims 3',
    'The Sims 4',
    'Age of Empires',
    'Age of Empires II',
    'Civilization V',
    'Civilization VI',
    # RPG / Action RPG
    'The Elder Scrolls III: Morrowind',
    'The Elder Scrolls IV: Oblivion',
    'The Elder Scrolls V: Skyrim',
    'Fallout 3',
    'Fallout: New Vegas',
    'Fallout 4',
    "Baldur's Gate",
    "Baldur's Gate II",
    "Baldur's Gate 3",
    'Dragon Age: Origins',
    'Dragon Age: Inquisition',
    'Mass Effect',
    'Mass Effect 2',
    'Mass Effect 3',
    'The Witcher',
    'The Witcher 2',
    'The Witcher 3: Wild Hunt',
    'Cyberpunk 2077',
    'Dark Souls',
    'Dark Souls II',
    'Dark Souls III',
    'Elden Ring',
    'Sekiro: Shadows Die Twice',
    # Shooters modernos
    'Call of Duty',
    'Call of Duty: Modern Warfare',
    'Call of Duty: Warzone',
    'Battlefield 1',
    'Battlefield V',
    'Battlefield 2042',
    'Overwatch',
    'Overwatch 2',
    'Valorant',
    'Apex Legends',
    'Rainbow Six Siege',
    'Destiny',
    'Destiny 2',
    'Titanfall 2',
    # Indie
    'Minecraft',
    'Terraria',
    'Stardew Valley',
    'Undertale',
    'Hollow Knight',
    'Celeste',
    'Dead Cells',
    'Hades',
    'Cuphead',
    'Limbo',
    'Inside',
    'Braid',
    'The Binding of Isaac',
    'Slay the Spire',
    'Disco Elysium',
    'Papers, Please',
    'Return of the Obra Dinn',
    'Factorio',
    'RimWorld',
    'Among Us',
    # Survival / Sandbox
    'Rust',
    'Ark: Survival Evolved',
    'Subnautica',
    "No Man's Sky",
    'Valheim',
    'The Forest',
    'Sons of the Forest',
    "Don't Starve",
    'DayZ',
    # Deportes / Carreras
    'FIFA 23',
    'EA Sports FC 24',
    'NBA 2K23',
    'Madden NFL 23',
    'Rocket League',
    'Need for Speed',
    'Need for Speed: Underground',
    'Gran Turismo Sport',
    'WWE 2K23',
    "Tony Hawk's Pro Skater",
    'F1 23',
    # Terror
    'Resident Evil',
    'Resident Evil 2',
    'Resident Evil 4',
    'Resident Evil Village',
    'Silent Hill',
    'Silent Hill 2',
    'Outlast',
    'Outlast 2',
    'Amnesia: The Dark Descent',
    'Dead Space',
    'Dead Space Remake',
    'Phasmophobia',
    # Multijugador / Online
    'League of Legends',
    'Dota 2',
    'Fortnite',
    'PUBG: Battlegrounds',
    'Fall Guys',
    'Genshin Impact',
    'Roblox',
    'Warframe',
    # Narrativos
    'Life is Strange',
    'Life is Strange: True Colors',
    'Detroit: Become Human',
    'Heavy Rain',
    'Beyond: Two Souls',
    'Firewatch',
    'What Remains of Edith Finch',
    'The Walking Dead',
    'Oxenfree',
)

GAME_CATEGORIES = (
    # Main genres
    'Action',
    'Adventure',
    'Role-Playing',
    'Strategy',
    'Simulation',
    'Sports',
    'Racing',
    'Puzzle',
    'Platformer',
    'Shooter',
    'Fighting',
    'Horror',
    'Survival',
    'Sandbox',
    'Casual',
    'Arcade',
    'Educational',
    'Music',
    'Party',
    'Narrative',
    # Action
    'Third-Person Action',
    'First-Person Action',
    'Hack and Slash',
    "Beat 'em up",
    'Run and Gun',
    'Shooter',
    'First-Person Shooter (FPS)',
    'Third-Person Shooter (TPS)',
    'Tactical Shooter',
    'Arena Shooter',
    'On-Rails Shooter',
    'Twin-Stick Shooter',
    'Bullet Hell',
    'Stealth Action',
    'Rhythm Action',
    # Adventure
    'Graphic Adventure',
    'Text Adventure',
    'Interactive Fiction',
    'Point and Click Adventure',
    'Action Adventure',
    'Narrative Adventure',
    'Episodic Adventure',
    'Exploration Adventure',
    # RPG
    'RPG',
    'JRPG',
    'ARPG',
    'Tactical RPG',
    'Turn-Based RPG',
    'Action RPG',
    'Roguelike',
    'Roguelite',
    'Dungeon Crawler',
    'Western RPG',
    'Isometric RPG',
    'Open-World RPG',
    'Multiplayer RPG',
    'MMORPG',
    # Strategy
    'Strategy',
    'Real-Time Strategy (RTS)',
    'Turn-Based Strategy (TBS)',
    'Grand Strategy',
    '4X',
    'Tower Defense',
    'Tactical Strategy',
    'Military Strategy',
    'Economic Strategy',
    'Resource Management',
    'Auto Battler',
    # Simulation
    'Simulation',
    'Life Simulation',
    'Social Simulation',
    'Building Simulation',
    'Management Simulation',
    'Economic Simulation',
    'Flight Simulation',
    'Space Simulation',
    'Driving Simulation',
    'Medical Simulation',
    'Farming Simulation',
    'Business Simulation',
    # Sports
    'Sports',
    'Football / Soccer',
    'Basketball',
    'Baseball',
    'Tennis',
    'Golf',
    'Boxing',
    'Martial Arts',
    'Extreme Sports',
    'Skateboarding',
    'Snowboarding',
    'Cycling',
    'Olympic Sports',
    'eSports',
    # Racing
    'Racing',
    'Arcade Racing',
    'Simulation Racing',
    'Kart Racing',
    'Futuristic Racing',
    'Motorcycle Racing',
    'Rally Racing',
    'Street Racing',
    'Vehicular Combat',
    # Platformer
    'Platformer',
    '2D Platformer',
    '3D Platformer',
    'Precision Platformer',
    'Metroidvania',
    'Endless Runner',
    # Puzzle
    'Puzzle',
    'Logic Puzzle',
    'Match-3',
    'Physics Puzzle',
    'Narrative Puzzle',
    'Escape Room',
    'Cooperative Puzzle',
    # Fighting
    'Fighting',
    '2D Fighting',
    '3D Fighting',
    'Team-Based Fighting',
    'Arena Fighter',
    'Platform Fighter',
    # Horror
    'Horror',
    'Psychological Horror',
    'Survival Horror',
    'First-Person Horror',
    'Cooperative Horror',
    # Survival
    'Survival',
    'Open-World Survival',
    'Crafting Survival',
    'Zombie Survival',
    'Battle Royale',
    # Sandbox & Open World
    'Open World',
    'Creative Sandbox',
    'Physics Sandbox',
    'Free-Building',
    # Multiplayer
    'Multiplayer',
    'Co-Op',
    'Local Co-Op',
    'Online Co-Op',
    'Player vs Player (PvP)',
    'Player vs Environment (PvE)',
    'Crossplay',
    'MMO',
    # Narrative & Artistic
    'Narrative',
    'Interactive Story',
    'Visual Novel',
    'Interactive Drama',
    'Art Game',
    'Walking Simulator',
    # Music & Rhythm
    'Music',
    'Rhythm',
    'Dance',
    'Karaoke',
    'Band Simulation',
    # Casual & Mobile
    'Casual',
    'Hyper-Casual',
    'Idle',
    'Clicker',
    'Incremental',
    # Educational & Serious Games
    'Educational',
    'Serious Games',
    'Training',
    'Educational Simulation',
    # Other tags
    'Retro',
    'Remake',
    'Remaster',
    'Experimental',
    'Indie',
    'AAA',
    'Free to Play',
    'Pay to Win',
    'Virtual Reality (VR)',
    'Augmented Reality (AR)',
    'Mixed Reality',
    'Procedural Generation',
    'Random Generation',
)

GAME_PLATFORMS = (
    # Generic / Cross-platform
    'PC',
    'Windows',
    'macOS',
    'Linux',
    'Web',
    'Browser',
    'Cloud Gaming',
    'Cross-Platform',
    # Consoles - Sony
    'PlayStation',
    'PlayStation 2',
    'PlayStation 3',
    'PlayStation 4',
    'PlayStation 5',
    'PlayStation Portable (PSP)',
    'PlayStation Vita',
    # Consoles - Microsoft
    'Xbox',
    'Xbox 360',
    'Xbox One',
    'Xbox Series X',
    'Xbox Series S',
    # Consoles - Nintendo
    'Nintendo Entertainment System (NES)',
    'Super Nintendo Entertainment System (SNES)',
    'Nintendo 64',
    'GameCube',
    'Wii',
    'Wii U',
    'Nintendo Switch',
    'Nintendo Switch Lite',
    'Nintendo Switch OLED',
    'Game Boy',
    'Game Boy Color',
    'Game Boy Advance',
    'Nintendo DS',
    'Nintendo 3DS',
    # Mobile
    'Mobile',
    'Android',
    'iOS',
    'iPadOS',
    # Handheld / Portable
    'Handheld',
    'Steam Deck',
    'ASUS ROG Ally',
    'Playdate',
    'Neo Geo Pocket',
    'PS Vita',
    # Retro / Classic
    'Atari 2600',
    'Atari 5200',
    'Atari 7800',
    'Atari Jaguar',
    'Atari Lynx',
    'Commodore 64',
    'Amiga',
    'MS-DOS',
    'ZX Spectrum',
    'Neo Geo',
    'TurboGrafx-16',
    'Sega Master System',
    'Sega Genesis',
    'Sega Mega Drive',
    'Sega Saturn',
    'Sega Dreamcast',
    'Game & Watch',
    # Arcade
    'Arcade',
    'Coin-Op Arcade',
    # Virtual / Augmented Reality
    'Virtual Reality (VR)',
    'Augmented Reality (AR)',
    'Mixed Reality (MR)',
    'PlayStation VR',
    'Meta Quest',
    'HTC Vive',
    'Valve Index',
    # Cloud / Streaming Services
    'Xbox Cloud Gaming',
    'PlayStation Now',
    'NVIDIA GeForce NOW',
    'Amazon Luna',
    'Google Stadia',
    # Digital Stores / Distribution
    'Steam',
    'Epic Games Store',
    'GOG',
    'itch.io',
    'Microsoft Store',
    'PlayStation Store',
    'Xbox Store',
    'Nintendo eShop',
    # Smart / Other Devices
    'Smart TV',
    'Apple TV',
    'Fire TV',
    'Set-Top Box',
    # Experimental / Other
    'Emulator',
    'Retro Console',
    'Dedicated Console',
    'Custom Hardware',
)
